# Generated by Django 3.1 on 2021-07-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0002_auto_20210721_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeId',
        ),
    ]
