# Generated by Django 3.1 on 2021-07-29 04:13

import django.utils.timezone
import model_utils.fields
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.models.partitioned
import psqlextra.types
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stripe_payment', '0003_delete_stripeid'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='StripeId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stripe_id', models.CharField(max_length=250, verbose_name='id в stripe')),
                ('billing_id', models.CharField(max_length=250, verbose_name='id в billing')),
                ('object_type', models.CharField(choices=[('price', 'Price'), ('product', 'Product'), ('subscription', 'Subscription')], max_length=64, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'ID stripe',
                'verbose_name_plural': 'IDs stripe',
                'ordering': ['-id'],
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['LIST'],
                'key': ['object_type'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
        ),
        psqlextra.backend.migrations.operations.PostgresAddListPartition(
            model_name="StripeId",
            name="price",
            values=["price"]
        ),
        psqlextra.backend.migrations.operations.PostgresAddListPartition(
            model_name="StripeId",
            name="product",
            values=["product"],
        ),
        psqlextra.backend.migrations.operations.PostgresAddListPartition(
            model_name="StripeId",
            name="subscription",
            values=["subscription"],
        ),
    ]
