version: '3.4'

services:

  movies_admin:
    build: services/movies_admin
    container_name: movies_admin
    restart: on-failure
    env_file: docker-compose-env/movies-admin.env
    volumes:
      - movies-admin-static:/opt/app/static/movies

  nginx:
    build: services/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - movies-admin-static:/src/static/movies-admin
      - notify-admin-static:/src/static/notify-admin
      - /etc/letsencrypt/live/yandexmovies.online:/etc/ssl/certs/
    depends_on:
      - movies_admin
      - movies_async_api
      - notify_admin
      - notify_api

  movies_films_etl:
    build: services/etl
    restart: on-failure
    environment:
      - MODE_ETL=FILMWORK_ETL
    env_file: docker-compose-env/movies-etl.env

  movies_persons_etl:
    build: services/etl
    restart: on-failure
    environment:
      - MODE_ETL=PERSON_ETL
    env_file: docker-compose-env/movies-etl.env

  movies_genres_etl:
    build: services/etl
    restart: on-failure
    environment:
      - MODE_ETL=GENRE_ETL
    env_file: docker-compose-env/movies-etl.env

  movies_async_api:
    build: services/async_api
    container_name: movies_async_api
    restart: on-failure
    env_file: docker-compose-env/async-api.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - movies-elastic-data:/usr/share/elasticsearch/data

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data

  notify_admin:
    build: services/notify_admin
    image: notify_admin
    container_name: notify_admin
    restart: on-failure
    volumes:
      - notify-admin-static:/var/app/static/notify-admin
    env_file: docker-compose-env/notify_admin.env

  notify_api:
    build: services/notify_api
    container_name: notify_api
    restart: on-failure
    env_file: docker-compose-env/notify_admin.env
    depends_on:
      - rabbitmq

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: test_kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  rabbitmq:
    build: services/rabbit_docker
    restart: "always"

  notify_admin_celery_worker:
    image: notify_admin
    hostname: celery_worker
    restart: "always"
    command:
      - celery
      - -A
      - config
      - worker
      - -P
      - prefork
      - -c
      - "1"
      - -l
      - INFO
    entrypoint: ""
    environment:
      PYTHONPATH: "."
    env_file: docker-compose-env/notify_admin.env
    depends_on:
      - rabbitmq
      - notify_api

  notify_admin_celery_beat:
    image: notify_admin
    hostname: celery_beat
    restart: "always"
    command:
      - celery
      - -A
      - config
      - beat
      - -l
      - INFO
    entrypoint: ""
    environment:
      PYTHONPATH: "."
    env_file: docker-compose-env/notify_admin.env
    depends_on:
      - rabbitmq
      - notify_api

  notify_worker_fast:
    build: services/notify_worker
    environment:
      MQ_QUEUE: "movies.q.notify_fast"
    restart: on-failure
    env_file: docker-compose-env/notify_admin.env
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  notify_worker_slow:
    build: services/notify_worker
    environment:
      MQ_QUEUE: "movies.q.notify_slow"
    restart: on-failure
    env_file: docker-compose-env/notify_admin.env
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2

volumes:
  movies-admin-static:
  notify-admin-static:
  movies-elastic-data:
  redis-data:
