@startuml
autonumber
== Регистрация ==
Пользователь -> Сайт : /user/registration\nЛогин и пароль
Сайт -> Бэкенд : Существует ли пользователь?

alt Пользователь уже существует
Бэкенд -> Сайт: Пользователь уже существует
Сайт -> Пользователь: Такой пользователь уже существует
else Пользователь еще не существует
Бэкенд -> Сайт: Пользователь не существует
Сайт -> Бэкенд : Создать пользователя
Бэкенд -> Сайт: Пользователь создан
Сайт -> Пользователь: Спасибо за регистрацию
end


== Идентификация ==
Пользователь -> Сайт : /login\nЛогин и пароль
Сайт -> Бэкенд : Существует ли пользователь?

alt Пользователь существует
Бэкенд -> Сайт: Да, существует
Сайт -> Бэкенд: Сохранить инфу о входе
Бэкенд -> Сайт: Сохранено
Бэкенд -> Redis: Старые токены в блэклист
Сайт -> Пользователь: Access & Refresh токены
else Пользователь не найден
Бэкенд -> Сайт: Нет
Сайт -> Пользователь: Неверное имя пользователя или пароль
end


== Выход из системы ==
Пользователь -> Сайт : /logout\nAccess токен
Сайт -> Бэкенд : Удалить токены пользователя
Бэкенд -> Redis: Токены в блэклист
Бэкенд -> Сайт: Удалено
Сайт -> Пользователь: Всего доброго!


== Смена Пароля ==
Пользователь -> Сайт : /user/password\nAccess токен\nСтарый пароль\nНовый пароль\nНовый пароль еще раз
Сайт -> Бэкенд : Обновить пароль пользователя
Бэкенд -> Сайт: Пароль изменен
Сайт -> Пользователь: Пароль изменен.\nПройдите повторную идентификацию.


== Аутентификация ==
Пользователь -> Сайт : Access токен
Сайт -> Бэкенд : Токен действителен?
Бэкенд -> Redis: Поиск токена в черном списке

alt Access токен действителен
Redis -> Бэкенд: Токен не найден
Бэкенд -> Сайт: Да
Сайт -> Пользователь: Успех

else Access токен не действителен
Redis -> Бэкенд: Токен найден в черном списке
Бэкенд -> Сайт: Нет
Сайт -> Пользователь: Обновите Access токен
end


== Обновление Accsess токена ==
Пользователь -> Сайт : /user/token/refresh\nRefresh токен
Сайт -> Бэкенд : Токен действителен?
Бэкенд -> Redis: Поиск токена

alt Refresh токен действителен
Redis -> Бэкенд: Токен не найден в черном списке
Бэкенд -> Redis: Старый Refresh токен в черный список
Бэкенд -> Сайт: Создать новые токены
Сайт -> Пользователь: Access и Refresh токен

else Refresh токен просрочен
Redis -> Бэкенд: Токен в черном списке
Бэкенд -> Сайт: Нет
Сайт -> Пользователь: Пройдите идентификация
end


== История входов ==
Пользователь -> Сайт : /user/journal/login \nAccess токен
Сайт -> Бэкенд : Найди историю входов
Бэкенд -> Сайт: результат
Сайт -> Пользователь: История входов
@enduml
