# Generated by Django 3.1 on 2021-07-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_init_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('draft', 'На оформлении'), ('inactive', 'Не активная'), ('active', 'Активная'), ('expired', 'Истек срок действия'), ('cancelled', 'Подписка отмененна'), ('cancel_at_period_end', 'Отменена после окончания периода')], default='inactive', max_length=64, verbose_name='Статус подписки'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='subscriptions.product', verbose_name='продукт'),
        ),
    ]
