# Generated by Django 3.1 on 2021-07-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210722_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='подписка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('draft', 'На оформлении'), ('inactive', 'Не активная'), ('active', 'Активная'), ('expired', 'Истек срок действия'), ('cancelled', 'Подписка отменена'), ('cancel_at_period_end', 'Отмена после окончания периода')], default='inactive', max_length=64, verbose_name='Статус подписки'),
        ),
    ]
