# Generated by Django 3.1 on 2021-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20210722_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('not_payed', 'Не оплачен'),
                    ('payed', 'Оплачен'),
                    ('pending', 'Ждем подтверждения оплаты'),
                    ('failed', 'Оплата не успешна'),
                    ('cancelled', 'Оплата отменена'),
                    ('refunded', 'Выполнен возврат')
                ],
                default='not_payed',
                max_length=64,
                verbose_name='Статус платежа'
            ),
        ),
    ]
