# Generated by Django 3.1 on 2021-07-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subscriptions', '0008_auto_20210729_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditevents',
            name='related_id',
        ),
        migrations.RemoveField(
            model_name='auditevents',
            name='related_name',
        ),
        migrations.AddField(
            model_name='auditevents',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditevents',
            name='object_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
