# Generated by Django 3.1 on 2021-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20210729_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='roles_updated',
            field=models.BooleanField(default=False, verbose_name='роли обновлены'),
        ),
    ]
