# Generated by Django 3.1 on 2021-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20210729_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='wait_payment_task',
            field=models.UUIDField(blank=True, default=None, null=True, verbose_name='id задачи на оплату'),
        ),
    ]
