# Generated by Django 3.2.4 on 2021-06-24 12:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


HELLO_MSG = """<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <title>Добро пожаловать!</title>
</head>
<body>

<p>Добро пожаловать, {{ username }}<br>
    Спасибо за регистрацию!
</p>

<p>
    С уважением, команда онлайн-кинотеатра.
</p>
</body>
</html>"""


def insert_notify_templates(apps, schema_editor):
    NotifyTemplate = apps.get_model('notification', 'NotifyTemplate')

    NotifyTemplate(
        title='hello_message',
        short_text='Спасибо за регистрацию, {{ username }}!',
        message=HELLO_MSG
    ).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=512, unique=True)),
                ('short_text', models.CharField(max_length=512)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'шаблон нотификации',
                'verbose_name_plural': 'шаблоны нотификаций',
                'db_table': 'notify_template',
            },
        ),
        migrations.RunPython(insert_notify_templates)
    ]
