# Generated by Django 3.2.4 on 2021-06-25 06:09

from django.db import migrations

MSG = """<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <title>Новые фильмы!</title>
</head>
<body>

<h2>Подборка новых фильмов для хорошего вечера:</h2>

{% for film in films %}
<p>
<h3>{{film.name}}</h3>
<p>
{{film.description}}
</p>
</p>
{% endfor %}

<p>
    С уважением, команда онлайн-кинотеатра.
</p>
</body>
</html>"""


def insert_notify_templates(apps, schema_editor):
    NotifyTemplate = apps.get_model('notification', 'NotifyTemplate')

    NotifyTemplate(
        title='new_movies',
        short_text='Посмотрите подборку новых фильмов!',
        message=MSG
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_notify_templates)
    ]
