# Generated by Django 3.2.4 on 2021-07-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_allowchannel_channel_client_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifytemplate',
            name='notify',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notify', verbose_name='нотификация'),
        ),
    ]
