# Generated by Django 3.1 on 2021-07-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210722_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_system',
            field=models.CharField(choices=[('yoomoney', 'Платежная система Юмани'), ('stripe', 'Платежная система Stripe')], default='yoomoney', max_length=64, verbose_name='Тип платежной системы'),
        ),
    ]
