# Generated by Django 3.1 on 2021-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_20210129_add_extra_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='access_type',
            field=models.CharField(
                choices=[
                    ('free', 'бесплатный доступ'),
                    ('standard', 'обычная подписка'),
                    ('extra', 'расширенная подписка')
                ],
                default='standard',
                max_length=50,
                verbose_name='тип доступа'
            ),
        ),
    ]
