### signup
POST {{auth_url}}/api/v1/auth/signup
content-type: application/json

{
  "email": "{{auth_email}}",
  "password": "{{auth_password}}"
}


### login
POST {{auth_url}}/api/v1/auth/login
content-type: application/json

{
  "email": "{{auth_email}}",
  "password": "{{auth_password}}"
}


### logout
DELETE {{auth_url}}/api/v1/auth/logout
content-type: application/json
authorization: Bearer {{access_token}}


### access check
GET {{auth_url}}/api/v1/auth/access_check
content-type: application/json
authorization: Bearer {{access_token}}

### refresh
POST {{auth_url}}/api/v1/auth/refresh
content-type: application/json
authorization: Bearer {{refresh_token}}


### revoked
POST {{auth_url}}/api/v1/users/{{user_id}}/revoke_access_keys
content-type: application/json
authorization: Bearer {{access_token}}
